_n_gpu: 1
adafactor: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
bf16: false
bf16_full_eval: false
dataloader_drop_last: false
dataloader_num_workers: 0
dataloader_pin_memory: true
ddp_bucket_cap_mb: null
ddp_find_unused_parameters: null
debug: '[]'
deepspeed: null
disable_tqdm: false
do_eval: true
do_predict: false
do_train: false
eval_accumulation_steps: null
eval_steps: 400
evaluation_strategy: steps
fp16: true
fp16_backend: auto
fp16_full_eval: false
fp16_opt_level: O1
gradient_accumulation_steps: 2
gradient_checkpointing: true
greater_is_better: null
group_by_length: true
half_precision_backend: amp
hub_model_id: null
hub_strategy: every_save
hub_token: <HUB_TOKEN>
ignore_data_skip: false
label_names: null
label_smoothing_factor: 0.0
learning_rate: 0.0001
length_column_name: length
load_best_model_at_end: false
local_rank: -1
log_level: -1
log_level_replica: -1
log_on_each_node: true
logging_dir: Model/runs/Mar17_07-52-06_7da6d8561539
logging_first_step: false
logging_nan_inf_filter: true
logging_steps: 400
logging_strategy: steps
lr_scheduler_type: linear
max_grad_norm: 1.0
max_steps: -1
metric_for_best_model: null
model_class: wav2vec2-xls-r-300m
mp_parameters: ''
no_cuda: false
num_train_epochs: 200
optim: adamw_hf
output_dir: Model
overwrite_output_dir: false
past_index: -1
per_device_eval_batch_size: 8
per_device_train_batch_size: 32
per_gpu_eval_batch_size: null
per_gpu_train_batch_size: null
prediction_loss_only: false
push_to_hub: false
push_to_hub_model_id: null
push_to_hub_organization: null
push_to_hub_token: <PUSH_TO_HUB_TOKEN>
remove_unused_columns: true
report_to: '[''mlflow'', ''tensorboard'']'
resume_from_checkpoint: null
run_name: Model
save_on_each_node: false
save_steps: 400
save_strategy: steps
save_total_limit: 2
seed: 42
sharded_ddp: '[]'
skip_memory_metrics: true
tf32: null
tpu_metrics_debug: false
tpu_num_cores: null
use_legacy_prediction_loop: false
warmup_ratio: 0.0
warmup_steps: 1000
weight_decay: 0.0
xpu_backend: null
